model:
  use_flash_attention: true
  nope: true
  softmax_scale_type: HS
  freeze_type: BASE


training:
  seed: 314
  save_model: true
  # batch size 8
  gradient_accumulation_steps: 1  # 8 GPUs
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  eval_steps: 10000

  warmup_ratio: 0.1
  weight_decay: 0
